[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
viaIR = true
fs_permissions = [{ access = "read-write", path = "./"}]
allow_internal_expect_revert = true
optimizer = true
optimizer_runs = 3000

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap-v2/v2-periphery/=lib/v2-periphery/contracts/",
    "@solady/src/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/",
    "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
    "@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/",
    "@layerzerolabs/oapp-evm-upgradeable/=lib/devtools/packages/oapp-evm-upgradeable/",
    "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/'
]

no_match_test = "test_skip"

[rpc_endpoints]
flow_testnet = "${FLOW_TESTNET_RPC_URL}"

[lint]
exclude_lints = ["pascal-case-struct","mixed-case-function","mixed-case-variable","screaming-snake-case-const","screaming-snake-case-immutable","asm-keccak256","erc20-unchecked-transfer"]
